### ISSUE TITLE
fontFamily 'simple-line-icons' is not a system font and has not been loaded through Expo.Font.loadAsync.

### ISSUE THREAD

**Issue by faheem121** [InterfaceKit/react-native-image-picker-form#4]
fontFamily 'simple-line-icons' is not a system font and has not been loaded through Expo.Font.loadAsync.
- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Expo.Font.loadAsync.

**Comment by danielst19** [comment]
Un poco tarde para responder, pero para solucionar el error debes cargar la fuente de la siguiente manera:
`await Font.loadAsync({
    SimpleLineIcons: require('@expo/vector-icons/fonts/SimpleLineIcons.ttf')
});`

**Comment by a-morenovalls** [comment]
Fixed and not linked with this library, closing.

**Comment by kwameaj67** [comment]
> Fixed and not linked with this library, closing.

im still getting an error. any help
