### ISSUE TITLE
How to choose multiple images

### ISSUE THREAD

**Issue by Minhnguyendhth8b** [InterfaceKit/react-native-image-picker-form#5]
Hello, I just wondering that how can upload more than 1 picture.

**Comment by a-morenovalls** [comment]
Hi @Minhnguyendhth8b , at this moment is not possible to upload multiple images, basically we are relaying on `react-native-image-crop-picker`, so I guess the library doesn't support it.

**Comment by Minhnguyendhth8b** [comment]
Okay thanks @Moreno97. I will try to work with react-native-image-crop-picker
